# Keploy Configuration for AutoCrate NX Generator
app:
  name: "autocrate-nx-generator"
  version: "1.0.0"
  port: 3000
  host: "localhost"

test:
  # Test configuration
  path: "./keploy-tests"
  mockPath: "./keploy-mocks"
  delay: 5
  timeout: 30
  apiTimeout: 10
  coverage: true

  # Test sets for different scenarios
  testSets:
    - name: "standard-crates"
      description: "Standard crate size calculations"
      endpoints:
        - "/api/calculate-crate"
        - "/api/plywood-optimization"
        - "/api/cleat-placement"

    - name: "heavy-duty"
      description: "Heavy-duty and export crate testing"
      endpoints:
        - "/api/calculate-crate"
        - "/api/cleat-placement"
        - "/api/nx-export"

    - name: "optimization"
      description: "Material optimization testing"
      endpoints:
        - "/api/plywood-optimization"

    - name: "nx-generation"
      description: "NX CAD expression generation"
      endpoints:
        - "/api/nx-export"

# Recording configuration
record:
  filters:
    - urlPattern: "/api/*"
      method: ["GET", "POST", "PUT", "DELETE"]
    - urlPattern: "/health"
      method: ["GET"]

  # Headers to capture
  headers:
    - "content-type"
    - "accept"
    - "user-agent"
    - "x-request-id"

  # Headers to ignore
  ignoreHeaders:
    - "date"
    - "server"
    - "x-powered-by"

# Mock configuration
mock:
  strategy: "intelligent" # intelligent, exact, or loose
  latency: 0 # Add artificial latency in ms

  # External dependencies to mock
  services:
    - name: "database"
      type: "postgresql"
      host: "localhost"
      port: 5432

    - name: "cache"
      type: "redis"
      host: "localhost"
      port: 6379

# Proxy configuration
proxy:
  port: 16789
  dns_port: 26789

# CI/CD configuration
ci:
  provider: "github-actions"
  generateWorkflow: true
  runOnPR: true
  runOnPush: true
  branches:
    - main
    - develop

# Reporting
report:
  format: ["json", "html", "junit"]
  outputPath: "./test-results"
  includeCodeCoverage: true
  includeBenchmarks: true

# Advanced options
advanced:
  parallelRecording: false
  deduplication: true
  sanitization:
    enabled: true
    fields:
      - "password"
      - "apiKey"
      - "token"
      - "secret"
