#!/bin/bash

# Cursor Worktree Setup Script
# This script is executed automatically when Cursor creates a new worktree

set -e

print_info() { echo -e "\033[0;34m[WORKTREE SETUP]\033[0m $1"; }
print_success() { echo -e "\033[0;32m[WORKTREE SETUP]\033[0m $1"; }
print_warning() { echo -e "\033[1;33m[WORKTREE SETUP]\033[0m $1"; }

print_info "Setting up worktree environment..."

WORKTREE_DIR="$(pwd)"
print_info "Worktree directory: $WORKTREE_DIR"

# Check if we're in a worktree
if [ -f ".git" ]; then
    print_info "Detected git worktree"
    
    # Extract issue number from directory path if in issues/ directory
    if [[ "$WORKTREE_DIR" =~ issues/([0-9]+) ]]; then
        ISSUE_NUMBER="${BASH_REMATCH[1]}"
        print_info "Detected issue #$ISSUE_NUMBER"
        export CURSOR_ISSUE_NUMBER="$ISSUE_NUMBER"
        
        if [ -f ".issue-context.md" ]; then
            print_info "Found issue context file"
            export CURSOR_ISSUE_CONTEXT="$(cat .issue-context.md)"
        fi
    fi
fi

# Install dependencies if package.json exists
if [ -f "package.json" ]; then
    print_info "Checking dependencies..."
    
    if [ ! -d "node_modules" ] || [ "package.json" -nt "node_modules" ]; then
        print_info "Installing npm dependencies..."
        npm install
        print_success "Dependencies installed"
    else
        print_info "Dependencies up to date"
    fi
fi

# Set up environment variables
export NODE_ENV="${NODE_ENV:-development}"
export CURSOR_WORKTREE_DIR="$WORKTREE_DIR"
export CURSOR_WORKTREE_SETUP="true"

# Create .env.local if it doesn't exist (for Next.js)
if [ -f "next.config.js" ] && [ ! -f ".env.local" ]; then
    print_info "Creating .env.local file..."
    echo "# Auto-generated by worktree setup" > .env.local
    echo "NODE_ENV=development" >> .env.local
fi

# Check for GitHub CLI
if command -v gh &> /dev/null; then
    print_info "GitHub CLI detected"
    export CURSOR_GH_AVAILABLE="true"
else
    print_warning "GitHub CLI not found"
    export CURSOR_GH_AVAILABLE="false"
fi

echo ""
print_success "Worktree setup complete!"
echo ""
echo "Environment variables:"
echo "  CURSOR_WORKTREE_DIR: $CURSOR_WORKTREE_DIR"
echo "  CURSOR_ISSUE_NUMBER: ${CURSOR_ISSUE_NUMBER:-not set}"
echo "  CURSOR_GH_AVAILABLE: $CURSOR_GH_AVAILABLE"
echo ""

if [ -f ".issue-context.md" ]; then
    echo "Issue context available in .issue-context.md"
    echo ""
fi

print_info "Ready to work!"
