blank_issues_enabled: true
contact_links:
  - name: AutoCrate Discussions
    url: https://github.com/Shivam-Bhardwaj/AutoCrate/discussions
    about: Ask questions and discuss ideas with the community
